### ISSUE TITLE
Kvantum themes are missing

### ISSUE THREAD

**Issue by coolstrong** [AhmedSaadi0/my-hyprland-config#4]
Hello!

Thanks for your astonoushing designs! Truly the best desktop i've ever seen.
I forked your config and I'm trying to build my own from it. I cannot locate anywhere kvantum themes - they are not mentioned in install script and in `configs/ags/modules/theme/themes.js`, but it doesn't seem that they are provided in the repository (or I am really blind though). 

Also, several questions i couldn't figure out on my own:
1. Which qt themes have to be installed? The same file mentions breeze - is it the only one required? And how this is related to lightly-qt? 
2. What arch package provides `plasma-apply-colorscheme` script? I failed to find any information about it, and apparently it is required to align qt color scheme to presented themes.

Any help is welcomed :)

**Comment by AhmedSaadi0** [comment]
Hey there!

I'm sorry but I stopped using Kvantum themes a while ago. I used to have them on my awesome wm, and when I created this config, it resembled the setup I had. However, I've made some changes since then.

If you're interested, you can find all the Kvantum themes I used [here](https://github.com/AhmedSaadi0/MyAwesomeConfig/tree/master/themes/kvantum-themes).

Regarding the Qt theme, for all the themes except 'game,' I'm using the `Breeze` style. Please note that there is a plasma_color defined as well.

Ok lets look at some code
``` Javascript
plasma_color: 'Circles.colors', // The colors for qt apps
qt_style_theme: 'Breeze', // The theme style 
kvantum_theme: 'a-circles', // Kvantum theme
qt_icon_theme: 'FairyWren', // The icons for qt theme
```
You can change them as you like, just make sure to have the files copied to the right place.

**Comment by AhmedSaadi0** [comment]
The `plasma-apply-colorscheme` is probably an app that comes with `Plasma` packages. Try installing plasma applications, if you did not find it I can extract it from my system for you if you want
