### ISSUE TITLE
[Suggestion]When installing this configure and the backup option has been clicked,the script try to backup the folded to be covered instead of ~.

### ISSUE THREAD

**Issue by greenhandzdl** [AhmedSaadi0/my-hyprland-config#52]

**Comment by AhmedSaadi0** [comment]
I did not get it ?? can you give me example ?

**Comment by greenhandzdl** [comment]
I am sorry that I find the worry places.

**Comment by AhmedSaadi0** [comment]
No problem! Can you try explaining it again in a different way? Or, if you can, share a concrete example or steps so I can better understand the issue, or are you suggesting that the script should back up the folder to the home directory (~) instead of backing up the folder being overwritten? Because the script backups the folders that are going to be overwritten
